# Generated by Django 4.1.3 on 2022-11-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('мало важно', 'Мало важно'), ('важно', 'Важно'), ('срочно', 'Срочно!!!')], default='мало важно', max_length=12),
        ),
    ]
