# Generated by Django 4.1.3 on 2022-11-03 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_answer_delete_comment_alter_like_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
