# Generated by Django 4.1.3 on 2022-11-03 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_answerimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerimage',
            old_name='post',
            new_name='answer',
        ),
    ]
