# Generated by Django 4.1.3 on 2022-11-03 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_rename_post_answerimage_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerimage',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_images', to='post.answer'),
        ),
    ]
