# Generated by Django 4.1.3 on 2022-11-04 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_answer_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnswerImage',
        ),
    ]
