# Generated by Django 4.1.3 on 2022-11-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.CharField(choices=[('begin', 'Beginer'), ('jun', 'Junior'), ('mid', 'Middle'), ('seni', 'Senior')], default='draft', max_length=12),
        ),
    ]
