# Generated by Django 4.1.3 on 2022-11-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('student', 'Student'), ('mentor', 'Mentor'), ('curator', 'Curator')], default='student', max_length=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(choices=[('begin', 'Beginer'), ('jun', 'Junior'), ('mid', 'Middle'), ('seni', 'Senior')], default='begin', max_length=12),
        ),
    ]
