# Generated by Django 4.1.3 on 2022-11-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_options_remove_user_position_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('student', 'Student'), ('mentor', 'Mentor'), ('curator', 'Curator')], default='student', max_length=12),
        ),
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.CharField(choices=[('begin', 'Beginer'), ('jun', 'Junior'), ('mid', 'Middle'), ('seni', 'Senior')], default='begin', max_length=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='activation_code',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Username'),
        ),
    ]
